<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>A .Net Core implementation of the Mono System.Windows.Forms.DataVisualization library. This is built on top of System.Drawing.Common.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression></PackageLicenseExpression>
    <PackageReleaseNotes>Initial Release</PackageReleaseNotes>
    <Version>1.0.0-alpha7</Version>
    <PackageId>Core.System.Windows.Forms.DataVisualization</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Test\**" />
    <EmbeddedResource Remove="Test\**" />
    <None Remove="Test\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Mono.Shared\MonoTODOAttribute.cs" Link="MonoTODOAttribute.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\System.Windows.Forms\System.Windows.Forms.csproj" />
  </ItemGroup>

</Project>
